#!/bin/bash

# Define variables
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Create RSA key pair
openssl genpkey -algorithm RSA -out "${KEY_NAME}.pem" -aes256 -pass pass:"${PASSPHRASE}" -pkeyopt rsa_keygen_bits:${BITS}

# Extract public key
openssl rsa -pubout -in "${KEY_NAME}.pem" -out "${KEY_NAME}.pub.pem"

echo "RSA key pair created successfully."
